### ISSUE TITLE
missing __is_enabled?

### ISSUE THREAD

**Issue by BillyCroan** [dsoprea/GeditSafetySave#11]
When I try to use your plugin with gedit 44.2 in debian bookworm, I get errors on stdout:

me@x360:~/.local/share/gedit/plugins$ gedit 
Traceback (most recent call last):
  File "/home/me/.local/share/gedit/plugins/safety_save.py", line 115, in __is_enabled
    return self.__enabled
           ^^^^^^^^^^^^^^
AttributeError: 'SafetySavePluginViewExtension' object has no attribute '_SafetySavePluginViewExtension__enabled'. Did you mean: '_SafetySavePluginViewExtension__is_enabled'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/share/gedit/plugins/safety_save.py", line 239, in do_activate
    if self.__is_enabled() is False:
       ^^^^^^^^^^^^^^^^^^^
  File "/home/me/.local/share/gedit/plugins/safety_save.py", line 124, in __is_enabled
    self.__debug("Enabled? %s" % (self.__enabled))
  File "/home/me/.local/share/gedit/plugins/safety_save.py", line 95, in __debug
    self.__log(_log.debug, message)
  File "/home/me/.local/share/gedit/plugins/safety_save.py", line 89, in __log
    method("[%s] %s" % (self.__get_name(), message))
                        ^^^^^^^^^^^^^^^^^
  File "/home/me/.local/share/gedit/plugins/safety_save.py", line 191, in __get_name
    return self.__document.get_short_name_for_display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'get_short_name_for_display'

**Comment by BillyCroan** [comment]
I edited line 115 from __enabled to __is_enabled, and how I get a new error:
Traceback (most recent call last):
  File "/home/bcroan/.local/share/gedit/plugins/safety_save.py", line 243, in do_activate
    if self.__document.is_untitled() is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'is_untitled'
